language: node_js
node_js:
  - "0.11"
services: mongodb
before_install:
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
before_script:
- grunt mongoimport
- grunt build:dev
env:
  global:
    CODECLIMATE_REPO_TOKEN=f25dc3e29ed854855d4a251fb89470af0d87fad671eded6870c4188f2e12cbe4
